<?php

/**
 * @category    S3ibusiness
 * @package     S3ibusiness_Speedbox
 * @author      Speedbox ( http://www.speedbox.ma)
 * @developer   Ahmed MAHI <1hmedmahi@gmail.com> (http://ahmedmahi.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php echo $this->getChildHtml('oldavailable'); ?>
<?php if ($this->getQuote()->getShippingAddress()->getCity()): ?>
<script type="text/javascript">
 //<![CDATA[
 speedbox.SetCity("<?php echo $this->escapeHtml($this->getQuote()->getShippingAddress()->getCity()) ?>");
    if ($$("input[id='s_method_speedbox_speedbox']:checked").length != 0){
              speedbox.speedboxCheck();
     }
  //]]>
 </script>
<?php endif;?>
