<?php

/**
 * @category    S3ibusiness
 * @package     S3ibusiness_Speedbox
 * @author      Speedbox ( http://www.speedbox.ma)
 * @developer   Ahmed MAHI <1hmedmahi@gmail.com> (http://ahmedmahi.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php $google_api_key = Mage::getStoreConfig('carriers/speedbox/google_api_key');?>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<?php echo $google_api_key; ?>" js></script>
<script type="text/javascript">
 //<![CDATA[
var speedbox = new Varien.Speedbox("<?php echo Mage::getUrl('speedbox/index/pointsrelais'); ?>","<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>");
 //]]>
 </script>
<?php echo $this->getChildHtml('oldshippingmethod'); ?>

